using ArkSaveEditor.Entities;
using ArkSaveEditor.Entities.LowLevel.AutoGeneratedClasses;
using ArkWebMapGatewayClient.Messages;
using ArkWebMapGatewayClient.Messages.Entities;
using ArkWebMapMasterServer.PresistEntities;
using ArkWebMapMasterServer.Tools;
using LibDeltaSystem.Db.System;
using System;
using System.Collections.Generic;
using System.Text;

namespace ArkWebMapMasterServer.MirrorEntities
{
    public class MirroredMsgDino : MirroredMessage
    {
        public string dinoToken;
        public MirroredVector3 pos;
        public int tribeId;

        public override void ReadMsg(MirrorProtocolReader reader)
        {
            opcode = MirroredOpcode.Dino;
            dinoToken = reader.ReadNextString();
            pos = reader.ReadNextVector3();
            tribeId = reader.ReadNextInt();
        }

        public override Tuple<UpdateEntityRealtimePosition, int> ProcessMsg(DbServer s, ArkMirrorToken auth)
        {
            //Convert this position data to one for the map. First, obtain the map data
            string map = s.latest_server_map;
            ArkMapData mapinfo;
            if (ArkMapDataTable.arkmaps.ContainsKey(map))
                mapinfo = ArkMapDataTable.arkmaps[map];
            else
                return null; //Cannot compute.

            //Now, convert the location here to the map data.
            Vector2 simplifedPos = new Vector2(pos.x, pos.y);
            Vector2 adjustedPos = mapinfo.ConvertFromGamePositionToNormalized(simplifedPos);

            //Get dino ID
            string dinoId;
            if (auth.dinoTokenMap.ContainsKey(dinoToken))
                dinoId = auth.dinoTokenMap[dinoToken];
            else
                return null;

            //Create GATEWAY packet
            return new Tuple<UpdateEntityRealtimePosition, int>(new UpdateEntityRealtimePosition
            {
                t = UpdateEntityRealtimePosition.UpdateTypeOpcode.Dino,
                id = dinoId,

                mx = adjustedPos.x,
                my = adjustedPos.y
            }, tribeId);
        }
    }
}
